import React from 'react'
import Script from 'next/script'

const page = () => {
  return (
    <div>
        <Script>
            alert("fuck off bitch")
        </Script>

      hello
    </div>
  )
}

export default page

export const metadata = {
    title: "fuck off",
    description: "Generated by fuckoff create next app",
  };
  
